import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Subject } from '@/types/database';
import { toast } from '@/hooks/use-toast';

export function useSubjects() {
  return useQuery({
    queryKey: ['subjects'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('subjects')
        .select(`
          *,
          professor:professors(*),
          group:student_groups(*)
        `)
        .order('name');
      
      if (error) throw error;
      return data as Subject[];
    },
  });
}

export function useCreateSubject() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (subject: { name: string; professor_id: string; group_id: string }) => {
      const { data, error } = await supabase
        .from('subjects')
        .insert({ ...subject, code: '' }) // Code will be auto-generated by trigger
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['subjects'] });
      toast({ title: 'تم إضافة المادة بنجاح' });
    },
    onError: (error) => {
      toast({ title: 'خطأ في إضافة المادة', description: error.message, variant: 'destructive' });
    },
  });
}

export function useUpdateSubject() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async ({ id, ...updates }: { id: string; name?: string; professor_id?: string; group_id?: string }) => {
      const { data, error } = await supabase
        .from('subjects')
        .update(updates)
        .eq('id', id)
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['subjects'] });
      toast({ title: 'تم تحديث المادة بنجاح' });
    },
    onError: (error) => {
      toast({ title: 'خطأ في تحديث المادة', description: error.message, variant: 'destructive' });
    },
  });
}

export function useDeleteSubject() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('subjects')
        .delete()
        .eq('id', id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['subjects'] });
      toast({ title: 'تم حذف المادة بنجاح' });
    },
    onError: (error) => {
      toast({ title: 'خطأ في حذف المادة', description: error.message, variant: 'destructive' });
    },
  });
}
